[package]
name = "http-server"
version = "0.1.0"
description = "A simple http server."
authors = ["SmallMain"]
edition = "2021"

[dependencies]
clap = { version = "4.4.14", features = ["derive"] }
mime_guess = "2.0.4"
